import secrets
from datetime import time, timedelta

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone

from apps.bookings.models import Booking
from apps.care_providers.models import (
    AvailabilitySlot,
    CareProvider,
    StaffMember,
)
from apps.service_users.models import ServiceUserProfile
from apps.users.models import User


DEMO_EMAILS = {
    "admin": "admin.demo@caresphere.local",
    "provider": "provider.demo@caresphere.local",
    "family": "family.demo@caresphere.local",
}

DEMO_BOOKING_MARKER = "CareSphere demonstration journey"


class Command(BaseCommand):
    help = "Create or reset the three local accounts used for the CareSphere demo."

    def add_arguments(self, parser):
        parser.add_argument(
            "--password",
            help="Password for all three demo accounts (a random one is generated by default).",
        )
        parser.add_argument(
            "--allow-production",
            action="store_true",
            help="Explicitly permit demo records when DEBUG is False.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        if not settings.DEBUG and not options["allow_production"]:
            raise CommandError(
                "Refusing to create demo accounts while DEBUG is False. "
                "Use --allow-production only in a controlled non-public environment."
            )

        password = options["password"] or secrets.token_urlsafe(14)

        admin = self._upsert_user(
            email=DEMO_EMAILS["admin"],
            first_name="Amina",
            last_name="Administrator",
            user_type="admin",
            password=password,
            is_staff=True,
            is_superuser=True,
        )
        provider_user = self._upsert_user(
            email=DEMO_EMAILS["provider"],
            first_name="Priya",
            last_name="Provider",
            user_type="provider",
            password=password,
            is_staff=False,
            is_superuser=False,
        )
        family_user = self._upsert_user(
            email=DEMO_EMAILS["family"],
            first_name="Freddie",
            last_name="Family",
            user_type="family",
            password=password,
            is_staff=False,
            is_superuser=False,
        )

        provider, _ = CareProvider.objects.update_or_create(
            user=provider_user,
            defaults={
                "company_name": "CareSphere Demo Care Ltd",
                "trading_name": "Demo Home Care Watford",
                "business_type": CareProvider.BusinessType.AGENCY,
                "care_types": [
                    CareProvider.CareType.DOMICILIARY,
                    CareProvider.CareType.RESPITE,
                ],
                "specializations": ["dementia", "personal care"],
                "address_line1": "1 Demo Way",
                "city": "Watford",
                "postcode": "WD17 1NA",
                "county": "Hertfordshire",
                "phone": "01923 000000",
                "email": DEMO_EMAILS["provider"],
                "max_capacity": 20,
                "current_clients": 4,
                "staff_count": 1,
                "is_accepting_clients": True,
                "is_verified": True,
                "verification_status": CareProvider.VerificationStatus.VERIFIED,
                "verification_date": timezone.now(),
                "verified_by": admin,
                "cqc_verified": False,
                "hourly_rate_min": "24.00",
                "hourly_rate_max": "32.00",
            },
        )

        staff, _ = StaffMember.objects.update_or_create(
            provider=provider,
            email="staff.demo@caresphere.local",
            defaults={
                "first_name": "Sam",
                "last_name": "Carer",
                "role": StaffMember.Role.SENIOR_CAREGIVER,
                "employment_type": StaffMember.EmploymentType.FULL_TIME,
                "qualifications": ["Care Certificate", "Dementia awareness"],
                "experience_years": 6,
                "is_available": True,
                "dbs_verified": True,
                "right_to_work_verified": True,
                "training_certifications": ["Safeguarding adults"],
                "languages_spoken": ["English"],
                "is_active": True,
            },
        )

        care_recipient, _ = ServiceUserProfile.objects.update_or_create(
            managed_by=family_user,
            first_name="Mary",
            last_name="Family-Demo",
            defaults={
                "relationship_to_manager": "Mother",
                "care_requirements": {"support": ["personal care", "companionship"]},
                "medical_conditions": ["Dementia"],
                "mobility_needs": "Uses a walking frame indoors.",
                "communication_needs": "Allow time for calm, clear explanations.",
                "additional_notes": DEMO_BOOKING_MARKER,
                "is_active": True,
            },
        )

        start_date = timezone.localdate() + timedelta(days=1)
        start_time = time(10, 0)
        end_time = time(12, 0)
        start_at = timezone.make_aware(
            timezone.datetime.combine(start_date, start_time)
        )
        end_at = timezone.make_aware(
            timezone.datetime.combine(start_date, end_time)
        )

        AvailabilitySlot.objects.update_or_create(
            provider=provider,
            staff_member=staff,
            start_date=start_date,
            start_time=time(8, 0),
            defaults={
                "end_date": start_date,
                "end_time": time(18, 0),
                "slot_type": AvailabilitySlot.SlotType.HOURLY,
                "is_available": True,
                "is_booked": False,
                "is_recurring": False,
                "location_postcode": "WD17 1NA",
                "notes": DEMO_BOOKING_MARKER,
            },
        )

        Booking.objects.filter(
            user=family_user,
            provider=provider,
            notes=DEMO_BOOKING_MARKER,
        ).delete()
        booking = Booking.objects.create(
            user=family_user,
            provider=provider,
            service_user=care_recipient,
            care_type="Dementia and personal care",
            frequency=Booking.Frequency.WEEKLY,
            start_time=start_at,
            end_time=end_at,
            requirements="Morning personal care and companionship.",
            notes=DEMO_BOOKING_MARKER,
            status=Booking.Status.PENDING,
        )

        self.stdout.write(self.style.SUCCESS("CARESPHERE DEMO READY"))
        self.stdout.write(f"Password for all accounts: {password}")
        self.stdout.write(f"Administrator: {DEMO_EMAILS['admin']} -> /admin-dashboard")
        self.stdout.write(
            f"Care company: {DEMO_EMAILS['provider']} -> /provider-dashboard"
        )
        self.stdout.write(f"Client/family: {DEMO_EMAILS['family']} -> /dashboard")
        self.stdout.write(f"Pending care request: {booking.id}")
        self.stdout.write(
            "Use demonstration information only; do not enter real personal or care data."
        )

    def _upsert_user(
        self,
        *,
        email,
        first_name,
        last_name,
        user_type,
        password,
        is_staff,
        is_superuser,
    ):
        user, _ = User.objects.get_or_create(
            email=email,
            defaults={"username": email},
        )
        user.username = email
        user.first_name = first_name
        user.last_name = last_name
        user.user_type = user_type
        user.is_active = True
        user.is_verified = True
        user.is_staff = is_staff
        user.is_superuser = is_superuser
        user.set_password(password)
        user.save()
        return user
