"use client";
import { ArrowUpRight, CalendarDays, ChevronRight, Clock, ShieldCheck, Users } from "lucide-react";
import "../app/design-preview/preview.css";

export default function ProviderCommandCentre({ name, greeting, live, staffCount, coverage, scheduled, uncovered, attention, matches, recipientName, formatDate, week, onFilter }) {
  const completed = live.today.filter(visit => visit.status === "completed").length;
  return <div className="cc-shell cc-integrated">
    <section className="cc-greeting"><div><p className="cc-eyebrow">{new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</p><h1>{greeting}, {name}.</h1><p>Your care service, clearly in view.</p></div><button className="cc-primary" onClick={()=>onFilter("all")}><CalendarDays size={17}/>Review bookings <ArrowUpRight size={16}/></button></section>
    <section className="cc-summary">{[[live.today.length,"TODAY'S VISITS","scheduled"],[live.onVisit.length,"CARE IN PROGRESS","on visit"],[staffCount,"YOUR TEAM","staff members"],[completed,"COMPLETED","visits today"]].map(([count,label,detail])=><div key={label}><span className="cc-small">{label}</span><strong>{count} <small>{detail}</small></strong></div>)}</section>
    <div className="cc-grid">
      <section className="cc-card cc-attention"><div className="cc-card-heading"><div><p className="cc-eyebrow">NEEDS ATTENTION</p><h2>{attention?"A little action. A safer day.":"A calmer day for your team."}</h2></div><span className={`cc-chip ${attention?"amber":""}`}>{uncovered.length?`${uncovered.length} need cover`:"No coverage gaps"}</span></div>{attention?<div className="cc-alert"><span className="cc-alert-icon"><Users size={20}/></span><div><strong>{recipientName(attention)} needs staff cover</strong><p>{formatDate(attention.start_time)}</p><span>{matches?`${matches} suitable staff matches available`:"Review team availability"}</span></div><button onClick={()=>onFilter("unassigned")}>Review matches <ArrowUpRight size={16}/></button></div>:<div className="cc-healthy"><ShieldCheck size={23}/><div><strong>{scheduled.length?"Next 72 hours covered":"Ready for your next care request"}</strong><p>{scheduled.length?"No unassigned visits in this coverage window.":"No scheduled visits in the next 72 hours. New requests appear in your bookings."}</p></div></div>}<div className="cc-alert"><span className="cc-alert-icon"><Clock size={20}/></span><div><strong>{live.lateCheckIns.length+live.missed.length?`${live.lateCheckIns.length+live.missed.length} visits awaiting a start update`:"Today's visit activity"}</strong><p>{live.onVisit.length} in progress · {live.startingSoon.length} starting soon</p><span>Based on recorded booking status</span></div><button onClick={()=>onFilter("all")}>Review visits <ArrowUpRight size={16}/></button></div></section>
      <section className="cc-card cc-coverage"><div className="cc-card-heading"><div><p className="cc-eyebrow">COVERAGE RADAR</p><h2>Next 72 hours</h2></div><ShieldCheck size={18}/></div><div className="cc-coverage-body"><div className="cc-ring" style={{background:scheduled.length?`conic-gradient(#087765 0 ${coverage*3.6}deg, #c9a24b ${coverage*3.6}deg)`:'#e4ebe3'}}><div><strong>{scheduled.length?`${coverage}%`:"—"}</strong><span>{scheduled.length?"covered":"no visits"}</span></div></div><div className="cc-legend"><p><i/>Covered <strong>{scheduled.length-uncovered.length}</strong></p><p><i className="gold"/>Need cover <strong>{uncovered.length}</strong></p><p><i className="pale"/>Scheduled <strong>{scheduled.length}</strong></p></div></div><div className="cc-coverage-footer"><ShieldCheck size={17}/><span>{scheduled.length?"Forward staffing protection":"Coverage begins when visits are scheduled"}</span></div></section>
      <section className="cc-card cc-live"><div className="cc-card-heading"><div><p className="cc-eyebrow">LIVE OPERATIONS</p><h2>The right care. Right now.</h2></div><span className="cc-chip">{live.onVisit.length} in progress</span></div>{live.today.length?live.today.slice(0,3).map(visit=><div className="cc-visit" key={visit.id}><div className="cc-person"><span className="cc-person-avatar">{recipientName(visit).split(" ").slice(0,2).map(n=>n[0]).join("")}</span><div><strong>{recipientName(visit)}</strong><p>{formatDate(visit.start_time)}</p></div></div><span className="cc-carer">{visit.assigned_staff?"Staff assigned":"Awaiting assignment"}</span><span className={`cc-chip ${visit.status==="in_progress"?"":"neutral"}`}>{visit.status.replaceAll("_"," ")}</span></div>):<div className="cc-healthy"><CalendarDays size={23}/><div><strong>No visits scheduled today</strong><p>Upcoming care will appear here as bookings are arranged.</p></div></div>}<button className="cc-card-link" onClick={()=>onFilter("all")}>Open booking workspace <ChevronRight size={16}/></button></section>
      <section className="cc-card cc-outlook"><div className="cc-card-heading"><div><p className="cc-eyebrow">PLANNING AHEAD</p><h2>Your week at a glance</h2></div><CalendarDays size={18}/></div><div className="cc-week">{week.map((day,i)=><div key={i}><div className={day.needsCover?"warning":""} style={{height:`${Math.max(12,day.percentage-35)}px`}}/><strong>{day.percentage}%</strong><span>{day.label}</span></div>)}</div><div className="cc-outlook-note"><p>Coverage of scheduled bookings.<br/><strong>Days without visits have no cover required.</strong></p></div><button className="cc-card-link" onClick={()=>onFilter("unassigned")}>Review upcoming cover <ChevronRight size={16}/></button></section>
    </div>
  </div>;
}
