# Generated by Django 5.2 on 2026-08-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceuserprofile',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Service User Profile', 'verbose_name_plural': 'Service User Profiles'},
        ),
        migrations.RemoveField(
            model_name='serviceuserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='communication_needs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='linked_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_service_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='mobility_needs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='relationship_to_manager',
            field=models.CharField(blank=True, default='', help_text='Relationship between the service user and the person managing their care.', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceuserprofile',
            name='care_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='serviceuserprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceuserprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AlterField(
            model_name='serviceuserprofile',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
