# Generated by Django 5.2 on 2026-03-01 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCircle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Family Care Circle', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_consensus', models.BooleanField(default=True)),
                ('consensus_threshold', models.IntegerField(default=75, help_text='Percentage of members required for consensus')),
                ('allow_external_invites', models.BooleanField(default=True)),
                ('auto_share_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_circle', to='service_users.serviceuserprofile')),
            ],
            options={
                'verbose_name': 'Care Circle',
                'verbose_name_plural': 'Care Circles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareCircleMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary Contact'), ('decision_maker', 'Decision Maker'), ('contributor', 'Contributor'), ('viewer', 'Viewer'), ('admin', 'Administrator')], max_length=20)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse/Partner'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('grandchild', 'Grandchild'), ('friend', 'Friend'), ('neighbor', 'Neighbor'), ('professional', 'Professional'), ('other', 'Other')], max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('can_invite_members', models.BooleanField(default=False)),
                ('can_manage_bookings', models.BooleanField(default=False)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('can_make_decisions', models.BooleanField(default=False)),
                ('can_edit_profiles', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('care_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.carecircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_circle_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Care Circle Member',
                'verbose_name_plural': 'Care Circle Members',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('care_circle', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('message_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='family.carecircle')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_threads', to='family.carecirclemember')),
            ],
            options={
                'verbose_name': 'Communication Thread',
                'verbose_name_plural': 'Communication Threads',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('decision_type', models.CharField(choices=[('provider_selection', 'Provider Selection'), ('care_plan', 'Care Plan Approval'), ('financial', 'Financial Decision'), ('medical', 'Medical Decision'), ('emergency', 'Emergency Decision'), ('other', 'Other')], max_length=50)),
                ('options', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('voting', 'Voting in Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('voting_deadline', models.DateTimeField(blank=True, null=True)),
                ('minimum_votes', models.IntegerField(default=1)),
                ('allow_abstain', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('chosen_option', models.JSONField(blank=True, null=True)),
                ('approval_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voting_started_at', models.DateTimeField(blank=True, null=True)),
                ('voting_ended_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('care_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='family.carecircle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Decision',
                'verbose_name_plural': 'Family Decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('medical', 'Medical Note'), ('financial', 'Financial Note'), ('care_plan', 'Care Plan Note'), ('appointment', 'Appointment Note'), ('emergency', 'Emergency Note')], max_length=20)),
                ('privacy_level', models.CharField(choices=[('public', 'All Circle Members'), ('restricted', 'Selected Members Only'), ('private', 'Creator Only')], max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('attachments', models.JSONField(default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to='family.carecirclemember')),
                ('care_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='family.carecircle')),
                ('visible_to', models.ManyToManyField(blank=True, related_name='visible_notes', to='family.carecirclemember')),
            ],
            options={
                'verbose_name': 'Family Note',
                'verbose_name_plural': 'Family Notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='family.carecirclemember')),
            ],
            options={
                'verbose_name': 'Message Read Receipt',
                'verbose_name_plural': 'Message Read Receipts',
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', through='family.MessageReadReceipt', to='family.carecirclemember')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='family.carecirclemember')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='family.communicationthread')),
            ],
            options={
                'verbose_name': 'Thread Message',
                'verbose_name_plural': 'Thread Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='family.threadmessage'),
        ),
        migrations.CreateModel(
            name='ThreadParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.carecirclemember')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.communicationthread')),
            ],
            options={
                'verbose_name': 'Thread Participation',
                'verbose_name_plural': 'Thread Participation',
                'unique_together': {('thread', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='participants',
            field=models.ManyToManyField(related_name='threads', through='family.ThreadParticipation', to='family.carecirclemember'),
        ),
        migrations.CreateModel(
            name='DecisionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chosen_option', models.CharField(max_length=500)),
                ('vote_weight', models.IntegerField(default=1)),
                ('is_abstained', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='family.carecirclemember')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='family.familydecision')),
            ],
            options={
                'verbose_name': 'Decision Vote',
                'verbose_name_plural': 'Decision Votes',
                'unique_together': {('decision', 'voter')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'reader')},
        ),
    ]
