# Generated by Django 5.2 on 2026-08-14 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_providers', '0001_initial'),
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='care_providers.careprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Provider',
                'verbose_name_plural': 'Saved Providers',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', 'saved_at'], name='family_save_user_id_7f1868_idx'), models.Index(fields=['provider'], name='family_save_provide_cad6b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_saved_provider_per_user')],
            },
        ),
    ]
