# Generated by Django 5.2 on 2026-08-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_savedprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecirclemember',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse/Partner'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('grandchild', 'Grandchild'), ('friend', 'Friend'), ('neighbor', 'Neighbor'), ('professional', 'Professional')], max_length=20),
        ),
    ]
