# Generated by Django 5.2 on 2026-03-01 11:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('care_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('staff_attitude', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_for_money', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('service_duration', models.CharField(blank=True, max_length=50)),
                ('relationship', models.CharField(choices=[('service_user', 'Service User'), ('family_member', 'Family Member'), ('professional', 'Professional Referral'), ('other', 'Other')], default='service_user', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('moderation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='care_providers.careprovider')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'overall_rating'], name='trust_layer_provide_b7de97_idx'), models.Index(fields=['is_verified', 'moderation_status'], name='trust_layer_is_veri_94bb37_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cqc_location_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('cqc_rating', models.CharField(choices=[('Outstanding', 'Outstanding'), ('Good', 'Good'), ('Requires Improvement', 'Requires Improvement'), ('Inadequate', 'Inadequate'), ('Not Rated', 'Not Rated')], default='Not Rated', max_length=20)),
                ('cqc_last_inspection', models.DateField(blank=True, null=True)),
                ('cqc_report_url', models.URLField(blank=True)),
                ('dbs_verified', models.BooleanField(default=False)),
                ('dbs_certificate_number', models.CharField(blank=True, max_length=100)),
                ('dbs_issue_date', models.DateField(blank=True, null=True)),
                ('dbs_expiry_date', models.DateField(blank=True, null=True)),
                ('dbs_enhanced', models.BooleanField(default=False)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('insurance_coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('training_certifications', models.JSONField(default=list)),
                ('last_training_refresh', models.DateField(blank=True, null=True)),
                ('gdpr_compliant', models.BooleanField(default=False)),
                ('health_safety_certified', models.BooleanField(default=False)),
                ('iso_certified', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('recommendation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('staff_turnover_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('staff_training_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overall_trust_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_verifications', to='care_providers.careprovider')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Verification',
                'verbose_name_plural': 'Trust Verifications',
                'indexes': [models.Index(fields=['overall_trust_score'], name='trust_layer_overall_a5c519_idx'), models.Index(fields=['verification_status'], name='trust_layer_verific_ab4d82_idx'), models.Index(fields=['cqc_rating'], name='trust_layer_cqc_rat_d0f669_idx')],
            },
        ),
    ]
