# Generated by Django 4.2.7 on 2026-10-08 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('care_providers', '0005_backfill_provider_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('care', 'Care'), ('training', 'Training'), ('supervision', 'Supervision'), ('hr', 'HR'), ('time_off', 'Time off')], default='care', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pay_mode', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed block'), ('incentive', 'Incentive block')], default='hourly', max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_blocks', to='care_providers.careprovider')),
                ('staff', models.ManyToManyField(blank=True, related_name='shift_blocks', to='care_providers.staffmember')),
            ],
            options={
                'ordering': ['start_time', 'title'],
                'indexes': [models.Index(fields=['provider', 'start_time'], name='care_provid_provide_9f7b14_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftblock',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='shift_block_positive_duration'),
        ),
    ]
