# Generated by Django 4.2.7 on 2026-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_providers', '0006_shiftblock_shiftblock_shift_block_positive_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('caregiver', 'Caregiver'), ('nurse', 'Nurse'), ('senior_caregiver', 'Senior Caregiver'), ('manager', 'Manager'), ('coordinator', 'Care Coordinator'), ('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('trainer', 'Trainer'), ('other', 'Other')], max_length=50),
        ),
    ]
