# Generated by Django 5.2 on 2026-08-17 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_booking_care_recipient_name_and_more'),
        ('care_providers', '0001_initial'),
        ('service_users', '0002_alter_serviceuserprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='service_users.serviceuserprofile'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_user', 'status'], name='bookings_bo_service_dad287_idx'),
        ),
    ]
